# Generated by Django 5.1.7 on 2025-04-30 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='公開日')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='画像')),
            ],
            options={
                'verbose_name': 'ブログ',
                'verbose_name_plural': 'ブログ',
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='項目名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.IntegerField(verbose_name='単価')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='税率 (%)')),
            ],
            options={
                'verbose_name': '見積項目',
                'verbose_name_plural': '見積項目',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='サービス名')),
                ('description', models.TextField(verbose_name='説明')),
                ('price', models.IntegerField(verbose_name='料金')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '料金',
                'verbose_name_plural': '料金',
            },
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=50, verbose_name='見積番号')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='発行日')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有効期限')),
                ('client_name', models.CharField(max_length=100, verbose_name='クライアント名')),
                ('client_address', models.TextField(verbose_name='クライアント住所')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='クライアントメール')),
                ('client_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='クライアント電話番号')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('items', models.ManyToManyField(related_name='estimates', to='D_Freedom_site.estimateitem', verbose_name='見積項目')),
            ],
            options={
                'verbose_name': '見積書',
                'verbose_name_plural': '見積書',
            },
        ),
    ]
