# Generated by Django 5.2 on 2025-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_Freedom_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='drawing_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='図面サイズ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='service_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='サービス名'),
        ),
    ]
