# Generated by Django 5.2 on 2025-04-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_Freedom_site', '0002_price_drawing_size_alter_price_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='description',
        ),
        migrations.RemoveField(
            model_name='price',
            name='service_name',
        ),
        migrations.AlterField(
            model_name='price',
            name='drawing_size',
            field=models.CharField(default='', max_length=100, verbose_name='図面サイズ'),
        ),
        migrations.AlterField(
            model_name='price',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備考'),
        ),
    ]
